"""empty message

Revision ID: 34414958d371
Revises: 67e55972a13f
Create Date: 2024-06-28 00:57:25.967395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34414958d371'
down_revision = '67e55972a13f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
